# MKDOCS - Configuration Options
# https://www.mkdocs.org/user-guide/configuration/
# -------------------------
site_name: IronHacks Platform
site_url: https://ironhacks.github.io/docs
docs_dir: docs
site_dir: site
theme:
  name: readthedocs
  highlightjs: true
# KEYBOARD SHORTCUTS http://keycode.info
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
# nav:
#     - Home: index.md
#     - About: about.md
# repo_url: git@github.com:ironhacks/docs.git
repo_url: https://github.com/ironhacks/docs
repo_name: docs
remote_branch: gh-pages
# google_analytics:
edit_uri: blob/master/src/
site_description: Ironhacks Platform Documentation Site
copyright: RCODI 2021
extra:
    version: 1.1
extra_css:
    - styles/custom.css
# extra_javascript:
markdown_extensions:
    - smarty
    - extra
    - toc
    - meta
    - tables
    - fenced_code
