name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: MkDocs Simple action
        uses: athackst/mkdocs-simple-plugin@v0.3.1
        with:
          publish_branch: gh-pages
          repo_url: https://github.com/${{ github.repository }}
          site_name: ${{ github.repository }}
          site_url: https://{{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
